---

- name: Ensure sudo group is present
  group:
    name: sudo
    state: present

- name: Ensure sudo group has sudo privileges
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL:ALL) ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Create an account for an admin user
  user:
    name: "{{ admin_user_username }}"
    password: "{{ admin_user_password }}"
    groups: sudo
    update_password: on_create
    state: present
  register: new_user

# Set the initial shell separately from creating the user. Otherwise, if the
# user changes the shell, it will get reset the next time the script is run.
# This will also show up as a change to the user account, which will trigger the
# password expiration.

- name: Set the initial shell
  user:
    name: "{{ admin_user_username }}"
    shell: /bin/bash
  when: new_user.changed

- name: Force a password change on the first login
  shell: chage -d 0 "{{ admin_user_username }}"
  when: new_user.changed

- name: Add authorized key
  authorized_key:
    user: "{{ admin_user_username }}"
    key: "{{ lookup('file', admin_user_public_key) }}"
