---

ansible_python_interpreter: /usr/bin/python3

app_user:
  username: abs
  password: "{{ vault.app_user.password }}"

repo:
  url: git@github.com:rjmorris/ansible-practice.git
  branch: master

app:
  root: /opt/abs
  local_tmpdir: /tmp/{{ app_user.username }}
  name: abs
  description: ABS@RTI web application
  port: 3000
