---

ansible_python_interpreter: /usr/bin/python3

deployer:
  username: rjmorris
  password: "{{ vault.deployer.password }}"
  public_key: ~/.ssh/id_rsa.pub

app_user:
  username: abs
  password: "{{ vault.app_user.password }}"
