---

- hosts: all
  become: true
  vars_prompt:
    - name: "admin_user_username"
      prompt: "admin's username"
      private: no
  tasks:
  - name: "Delete the user account"
    user:
      name: "{{ admin_user_username }}"
      state: absent
      remove: yes
